/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_muntashirakon_rapidfuzz_RapidFuzz */

#ifndef _Included_io_github_muntashirakon_rapidfuzz_RapidFuzz
#define _Included_io_github_muntashirakon_rapidfuzz_RapidFuzz
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativeRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativePartialRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativePartialRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativeTokenSortRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeTokenSortRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativePartialTokenSortRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativePartialTokenSortRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativeTokenSetRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeTokenSetRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativePartialTokenSetRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativePartialTokenSetRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativeTokenRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeTokenRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativePartialTokenRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativePartialTokenRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativeWeightedRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeWeightedRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativeQuickRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeQuickRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
