/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_muntashirakon_rapidfuzz_RapidFuzzCached */

#ifndef _Included_io_github_muntashirakon_rapidfuzz_RapidFuzzCached
#define _Included_io_github_muntashirakon_rapidfuzz_RapidFuzzCached
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeNewCachedRatio
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeNewCachedRatio
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeGetRatio
 * Signature: (JLjava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeGetRatio
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeFreeCachedRatio
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeFreeCachedRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeNewCachedPartialRatio
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeNewCachedPartialRatio
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeGetPartialRatio
 * Signature: (JLjava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeGetPartialRatio
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeFreeCachedPartialRatio
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeFreeCachedPartialRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeNewCachedTokenSortRatio
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeNewCachedTokenSortRatio
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeGetTokenSortRatio
 * Signature: (JLjava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeGetTokenSortRatio
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeFreeCachedTokenSortRatio
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeFreeCachedTokenSortRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeNewCachedPartialTokenSortRatio
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeNewCachedPartialTokenSortRatio
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeGetPartialTokenSortRatio
 * Signature: (JLjava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeGetPartialTokenSortRatio
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeFreeCachedPartialTokenSortRatio
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeFreeCachedPartialTokenSortRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeNewCachedTokenSetRatio
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeNewCachedTokenSetRatio
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeGetTokenSetRatio
 * Signature: (JLjava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeGetTokenSetRatio
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeFreeCachedTokenSetRatio
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeFreeCachedTokenSetRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeNewCachedPartialTokenSetRatio
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeNewCachedPartialTokenSetRatio
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeGetPartialTokenSetRatio
 * Signature: (JLjava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeGetPartialTokenSetRatio
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeFreeCachedPartialTokenSetRatio
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeFreeCachedPartialTokenSetRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeNewCachedTokenRatio
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeNewCachedTokenRatio
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeGetTokenRatio
 * Signature: (JLjava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeGetTokenRatio
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeFreeCachedTokenRatio
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeFreeCachedTokenRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeNewCachedPartialTokenRatio
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeNewCachedPartialTokenRatio
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeGetPartialTokenRatio
 * Signature: (JLjava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeGetPartialTokenRatio
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeFreeCachedPartialTokenRatio
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeFreeCachedPartialTokenRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeNewCachedWeightedRatio
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeNewCachedWeightedRatio
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeGetWeightedRatio
 * Signature: (JLjava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeGetWeightedRatio
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeFreeCachedWeightedRatio
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeFreeCachedWeightedRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeNewCachedQuickRatio
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeNewCachedQuickRatio
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeGetQuickRatio
 * Signature: (JLjava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeGetQuickRatio
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzzCached
 * Method:    nativeFreeCachedQuickRatio
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeFreeCachedQuickRatio
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
