/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_muntashirakon_rapidfuzz_RapidFuzz */

#ifndef _Included_io_github_muntashirakon_rapidfuzz_RapidFuzz
#define _Included_io_github_muntashirakon_rapidfuzz_RapidFuzz
#ifdef __cplusplus
extern "C" {
#endif
#undef io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_RATIO
#define io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_RATIO 1L
#undef io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_PARTIAL_RATIO
#define io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_PARTIAL_RATIO 2L
#undef io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_TOKEN_SORT_RATIO
#define io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_TOKEN_SORT_RATIO 3L
#undef io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_PARTIAL_TOKEN_SORT_RATIO
#define io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_PARTIAL_TOKEN_SORT_RATIO 4L
#undef io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_TOKEN_SET_RATIO
#define io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_TOKEN_SET_RATIO 5L
#undef io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_PARTIAL_TOKEN_SET_RATIO
#define io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_PARTIAL_TOKEN_SET_RATIO 6L
#undef io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_TOKEN_RATIO
#define io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_TOKEN_RATIO 7L
#undef io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_PARTIAL_TOKEN_RATIO
#define io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_PARTIAL_TOKEN_RATIO 8L
#undef io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_WEIGHTED_RATIO
#define io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_WEIGHTED_RATIO 9L
#undef io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_QUICK_RATIO
#define io_github_muntashirakon_rapidfuzz_RapidFuzz_TYPE_QUICK_RATIO 10L
/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativeRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativePartialRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativePartialRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativeTokenSortRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeTokenSortRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativePartialTokenSortRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativePartialTokenSortRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativeTokenSetRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeTokenSetRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativePartialTokenSetRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativePartialTokenSetRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativeTokenRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeTokenRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativePartialTokenRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativePartialTokenRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativeWeightedRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeWeightedRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     io_github_muntashirakon_rapidfuzz_RapidFuzz
 * Method:    nativeQuickRatio
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeQuickRatio
  (JNIEnv *, jclass, jstring, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
